/**
 * Automatically translated from C++ to Java
 * 
 * Original file: calculator.cpp
 * Module: calculator
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.converted.app.model;

#include <iostream>

int main() {
    int num1, num2;
    char operation;

    std::cout << "Enter first number: ";
    std::cin >> num1;
    std::cout << "Enter operation: ";
    std::cin >> operation;
    std::cout << "Enter second number: ";
    std::cin >> num2;

    switch(operation) {
        case '+':
            std::cout << "Result: " << num1 + num2;
            break;
        case '-':
            std::cout << "Result: " << num1 - num2;
            break;
        case '*':
            std::cout << "Result: " << num1 * num2;
            break;
        case '/':
            if(num2 != 0)
                std::cout << "Result: " << num1 / num2;
            else
                std::cout << "Error! Division by zero.";
            break;
        default:
            std::cout << "Invalid operation!";
    }

    return 0;
}
import java.util.Scanner;

public class Calculator {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        System.out.println("Enter first number: ");
        int num1 = scanner.nextInt();
        System.out.println("Enter operation: ");
        char operation = scanner.next().charAt(0);
        System.out.println("Enter second number: ");
        int num2 = scanner.nextInt();

        switch(operation) {
            case '+':
                System.out.println("Result: " + (num1 + num2));
                break;
            case '-':
                System.out.println("Result: " + (num1 - num2));
                break;
            case '*':
                System.out.println("Result: " + (num1 * num2));
                break;
            case '/':
                if(num2 != 0)
                    System.out.println("Result: " + (num1 / num2));
                else
                    System.out.println("Error! Division by zero.");
                break;
            default:
                System.out.println("Invalid operation!");
        }

        scanner.close();
    }
}